/*
 * This source file was generated by the Gradle 'init' task
 */
package minecraft;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        Render janela = new Render();
        janela.run();
    }
}
