/*
 * This source file was generated by the Gradle 'init' task
 */
package minecraft;

import minecraft.core.Game;

public class App {

    public static void main(String[] args) {
        Game game = new Game();
        game.run();
    }
}
